### ISSUE TITLE
projects.all returns SyntaxError: Unexpected token B in JSON at position 0

### ISSUE THREAD

**Issue by batjko** [node-gitlab/node-gitlab-legacy#166]
Hi there,

I'm running into a slumber error, apparently being unable to parse a response it gets from gitlab:
This error gets thrown as soon as I run `gitlab.projects.all()`:

```bash
/home/pmetzdorf/sandpit/igor-bot-service/node_modules/slumber/lib/API.js:192
          return fn(err, response, ret);
                 ^
SyntaxError: Unexpected token B in JSON at position 0
    at Object.parse (native)
    at /home/pmetzdorf/sandpit/igor-bot-service/node_modules/gitlab/lib/ApiBaseHTTP.js:88:42
    at _Class.wrap_response (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/slumber/lib/API.js:192:18)
    at _Class.wrap_response (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/slumber/lib/API.js:4:59)
    at Request._callback (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/slumber/lib/API.js:215:26)
    at Request.self.callback (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pmetzdorf/sandpit/igor-bot-service/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

It worked fine when i used it with gitlab.com (testing from home).
Now I am trying to use the same code with a self-hosted version of gitlab (older version: 6.7.2).
Could it be that this package is incompatible with the version? 

Cheers

**Comment by batjko** [comment]
So I think this _may_ come from the fact that my Gitlab instance requires SSL authentication.
Which would boil my question down to: how do I make sure my gitlab client uses ssl with certificates stored on the machine?
