### ISSUE TITLE
TypeError: gitlab.projects.issues.update is not a function

### ISSUE THREAD

**Issue by UtkarshMishr** [node-gitlab/node-gitlab-legacy#189]
When trying to update any existing issue within the Project then getting below error.

`TypeError: gitlab.projects.issues.update is not a function
    at Object.<anonymous> (C:\Users\mishrut\full_stack\gitlab_rally_alm\integration\updateGitlabIssues.js:8:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

Below is my code, passing Project and Issue ID directly.

`var gitlab = require('../setting/mySettingsGitLab')
params = {
    title: "xyz updates"
}
gitlab.projects.issues.update(9637,45,params, function(sevice){
    console.log("check it")
} )`

**Comment by UtkarshMishr** [comment]
Also tried, but same error

``var gitlab = require('../setting/mySettingsGitLab')
params = {
    title: "xyz updates"
}
gitlab.projects.issues.edit(9637,45,params, function(sevice){
    console.log("check it")
} )``
